### ISSUE TITLE
Can code obfuscation be supported?

### ISSUE THREAD

**Issue by zelang** [wangyoucao577/go-release-action#104]
I found a project: [https://github.com/burrowers/garble](https://github.com/burrowers/garble)
Obfuscate Go code by wrapping the Go toolchain. 
I hope you can add it to the action and run the obfuscation code directly.

**Comment by wangyoucao577** [comment]
Have a try with `pre_command` and `build_command` args, i.e., use `pre_command` to install the tool, then `build_command` to leverage it.

**Comment by zelang** [comment]
This is very useful.
