### ISSUE TITLE
Question: Where is the binary saved

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [wangyoucao577/go-release-action#111]
Is there a way to get the build artifact name/full path as an output for later use?

**Comment by wangyoucao577** [comment]
Currently it's in a temp path during the building process, so it's not easy for you to get them. A new feature maybe needed to expose the contents into the path that you indicated.

**Comment by pantelis-karamolegkos** [comment]
Thanks for the feedback. Closing this and I hope this is a good idea for a future improvment.
