### ISSUE TITLE
README should include required Github permissions

### ISSUE THREAD

**Issue by scosman** [wangyoucao577/go-release-action#119]
Github changed the default settings for new repos, and actions can't write unless you change a setting. This integration needs write permissions. Probably good to mention in README.

https://stackoverflow.com/a/75250838/4076298

Thanks for great project!

**Comment by sebafo** [comment]
Perhaps it would be great to mention the required permissions exactly.
If you won't change general action settings in the repository you need to add the following permissions to the job:
```
permissions:
    contents: write
    packages: write
```

**Comment by scosman** [comment]
Confirmed the more scoped permissions from @sebafo work! That's a much better solution than changing repo-wide setting.
