### ISSUE TITLE
pkg-config: exec: "pkg-config": executable file not found in $PATH

### ISSUE THREAD

**Issue by sberk42** [wangyoucao577/go-release-action#124]
hi,

I'm trying to get a build working that requires gousb, which needs to be build, the build is triggered but fails with:
go: downloading github.com/google/gousb v1.1.2
go build github.com/google/gousb:
# pkg-config --cflags  -- libusb-1.0
pkg-config: exec: "pkg-config": executable file not found in $PATH

I checked /usr/bin/pkg-config is in the image and libusb-1.0 installed - any idea how to make go build work?

**Comment by wangyoucao577** [comment]
Would you please share your full usage as well as the logs?  It should be work if everything is available.

**Comment by sberk42** [comment]
the action is here:
https://github.com/sberk42/sensor_exporter/blob/main/.github/workflows/build.yaml

and the complete build:
https://github.com/sberk42/sensor_exporter/actions/runs/5008670995/jobs/8976793379

**Comment by wangyoucao577** [comment]
Oh, you need to run the `apt` via `pre_command` of this action, something like: `pre_command: apt-get install -y libusb-1.0 libusb-1.0-0-dev`. The whole building process is inside container, so install them on runner won't be helpful.

**Comment by sberk42** [comment]
thanks for the hint - with the pre_command the build worked
