### ISSUE TITLE
how to `strip` the produced binary ?

### ISSUE THREAD

**Issue by grosser** [wangyoucao577/go-release-action#125]
I tried setting `build_command` to a custom `go build && strip <binary>`
that kinda worked, but runs into trouble when cross-compiling since for example amd64 can't strip arm64
and linux-arm can't strip darmin arm 🤦 

```
strip <binary>
strip: file format not recognized
```

any ideas for a workaround ? (only idea I have left is to use a custom runner for every os/arch but that is complicated ... partly because of apply only selling 24h compute time slices [docs](https://buildjet.com/for-github-actions/docs/runners/hardware#mac-os-m1-runners))

**Comment by wangyoucao577** [comment]
There're several options. As shown in [[How to reduce Go compiled file size?](https://stackoverflow.com/questions/3861634/how-to-reduce-go-compiled-file-size)](https://stackoverflow.com/questions/3861634/how-to-reduce-go-compiled-file-size), `go build -ldflags "-s -w"` is good to start. The `upx` compression has already supported by this action as well.

**Comment by grosser** [comment]
It tried the flags but it did not do what strip does ... The compression
makes the binary smaller or just the package ?

**Comment by wangyoucao577** [comment]
The `upx` compresses binary rather than package, see more in https://github.com/upx/upx

**Comment by grosser** [comment]
I guess that's not something easily solvable here then ... will close
