### ISSUE TITLE
Request: include extra files in archive (eg. README.md, LICENSE)

### ISSUE THREAD

**Issue by beefsack** [wangyoucao577/go-release-action#13]
Fantastic project! It's working really well for me.

I would really like to see the ability to include extra files in the archive. For my case, I would like to include README.md and LICENSE from my project root.

Thanks for your hard work!

**Comment by wangyoucao577** [comment]
It sounds reasonable. I'll add the feature.

**Comment by wangyoucao577** [comment]
@beefsack The feature is ready. Please try out `wangyoucao577/go-release-action@v1.6` with `extra_files: LICENSE README.md`, refer to https://github.com/wangyoucao577/go-release-action for more details. Let me know if it works for you.

**Comment by beefsack** [comment]
Fantastic, thanks @wangyoucao577! I'll test it now.

**Comment by beefsack** [comment]
I've tested the feature and it's working perfectly: https://github.com/beefsack/webify/releases/tag/v1.4.0

Thanks again :+1:

**Comment by neomen** [comment]
What's about folders, how can I add a folder to an archive? When I try to add files like this "extra_files: data/drupal.xml data/wordpress.xml .env README.md"  the files are available in the root of the archive

**Comment by wangyoucao577** [comment]
@neomen  Have a try with `extra_files: data README.md`

**Comment by neomen** [comment]
@wangyoucao577 Thanks, it worked great.
