### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by shapedthought** [wangyoucao577/go-release-action#138]
Hi there,

I'm still quite new to github actions so I don't know if this issue relates to this action, I'm getting the following error:

Saving to: 'go-linux.tar.gz'

0K                                                      100% 1.26M=0s

2023-10-18 07:[44](https://github.com/shapedthought/vcli/actions/runs/6557695137/job/17810030343#step:4:45):[49](https://github.com/shapedthought/vcli/actions/runs/6557695137/job/17810030343#step:4:50) (1.26 MB/s) - 'go-linux.tar.gz' saved [264/264]

--2023-10-18 07:44:49--  http://time/
Resolving time (time)... failed: Name or service not known.
wget: unable to resolve host address 'time'
--2023-10-18 07:44:49--  ftp://2023-10-09t17/04:35Z.linux-amd64.tar.gz
           => 'go-linux.tar.gz'
Resolving 2023-10-09t17 (2023-10-09t17)... failed: Name or service not known.
wget: unable to resolve host address '2023-10-09t17'
FINISHED --2023-10-18 07:44:49--

I'm not sure how to fix it, any help would be appreciated.

Thanks

**Comment by wangyoucao577** [comment]
Could you please show me the full action configuration?

**Comment by shapedthought** [comment]
`
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.34
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: LICENSE
          sha256sum: TRUE`

**Comment by wangyoucao577** [comment]
It's same with https://github.com/wangyoucao577/go-release-action/issues/136, you need to upgrade to latest version `wangyoucao577/go-release-action@v1`
