### ISSUE TITLE
Is there a demo that builds multiple binaries and packages them together?

### ISSUE THREAD

**Issue by csyezheng** [wangyoucao577/go-release-action#139]
I saw an issue mentioning using make. I don't quite understand how to use it and how make can be used with multiple OS.

**Comment by wangyoucao577** [comment]
Actually this has been discussed before https://github.com/wangyoucao577/go-release-action/issues/82, and I have a draft PR for it, only hasn't merged so far since no one uses it for real. I'll spend some time to complete it recently so that you can use it in your project!

**Comment by wangyoucao577** [comment]
Now you can have a try with `wangyoucao577/go-release-action@v1.49` which has supported this feature. Example refer to https://github.com/wangyoucao577/go-release-action/blob/e48e16c995dd667d496ab7a18f83942a21c3d766/.github/workflows/autotest.yml#L203-L228
