### ISSUE TITLE
goversion 1.21 failed

### ISSUE THREAD

**Issue by Wsine** [wangyoucao577/go-release-action#145]
I tried to use the configuration `goversion: 1.21`, however, it failed. I used to use `goversion: 1.17` and it works well.

See the context: https://github.com/Wsine/feishu2md/actions/runs/7382035938/workflow

Also, I tried to use `goversion: "go.mod"` but it also failed.

Context: https://github.com/Wsine/feishu2md/actions/runs/7382066531/workflow

Finally, I managed to set it to `goversion: 1.21.5`, then it worked.

Context: https://github.com/Wsine/feishu2md/actions/runs/7382078631/workflow

I think there may be something wrong in recent updates. Hope that helps.

**Comment by wangyoucao577** [comment]
It's caused by the missing of new `1.20` and `1.21` shortcuts, see https://github.com/wangyoucao577/go-release-action/blob/7f756b37f8a68530c6f0fcbe2da02e3f7ff51211/setup-go.sh#L10. Will fix it soon, PR is also welcome.

**Comment by Wsine** [comment]
> . Will fix it soon, PR is also welcome.

I opened an PR #146  for this issue.

**Comment by wangyoucao577** [comment]
New version has been released. Try again please!
