### ISSUE TITLE
Why it can't trigger by scheduled.

### ISSUE THREAD

**Issue by fscarmen** [wangyoucao577/go-release-action#148]
My workflow is trying to detect updates to an app every hour, and when it's officially updated, I release it and abort if it's not. This project reports an error that schedule is not supported

![image](https://github.com/wangyoucao577/go-release-action/assets/62703343/2647e8e6-508a-4c4d-b385-3e2a76619825)

Customizable release tag to support publish binaries per push or workflow_dispatch(manually trigger).

**Comment by wangyoucao577** [comment]
Oh, the action only allows expected triggers at the moment, because some people uses wrong triggers at very early days. Welcome PR to add `schedule` trigger or remove the limitaiton https://github.com/wangyoucao577/go-release-action/blob/d5f5f5c502f00e7d0dd59b52e3e2f3b382b05c66/release.sh#L34
