### ISSUE TITLE
[Feature Request] Support more GitHub events

### ISSUE THREAD

**Issue by Simple-Tracker** [wangyoucao577/go-release-action#161]
我正在使用这个 workflow 进行自动发布 Release 及运行 Nightly Build 测试+构建 (v1.47), 但是在对 Pull Request 触发测试时, 发生了失败.  (https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/actions/runs/7847677901/workflow)
由于 workflow 本身已经能够使用 if 条件去决定是否执行 (例如我在 workflow 调用 Upload Artifact 的判断), 因此希望能够支持更多的事件. 若出于向下兼容考虑 (由于会失败好像也没什么场景...), 是否能考虑增加一个输入参数用于控制是否能够使用其它事件或使用哪些事件?

谢谢!

**Comment by wangyoucao577** [comment]
可以允许，欢迎PR!
