### ISSUE TITLE
ldflags is ignored for multi binaries builds

### ISSUE THREAD

**Issue by securitym0nkey** [wangyoucao577/go-release-action#171]
When setting **multi_binaries: true** the **ldflag** argument is ignored.

**Comment by wangyoucao577** [comment]
Nowadays there's better way to replace `ldflags`, see more in https://github.com/wangyoucao577/go-release-action/issues/152#issuecomment-1943581310

**Comment by securitym0nkey** [comment]
Thanks, indeed that seems much better. Changed my project to not use ldflags for injection of version information. Though i think for other use cases of linker options it might be still useful.

**Comment by wangyoucao577** [comment]
Sure. Actually it's just caused by missed passing flags here https://github.com/wangyoucao577/go-release-action/blob/ec68290905b5e90fcab97069f9546af4303dd91a/release.sh#L107C1-L108C1, and can be fixed if someone really needs it. PR is welcome as well.

**Comment by wangyoucao577** [comment]
Fixed by https://github.com/wangyoucao577/go-release-action/pull/180
