### ISSUE TITLE
Customizable asset name

### ISSUE THREAD

**Issue by wangyoucao577** [wangyoucao577/go-release-action#26]
Currently asset name format is `${BINARY_NAME}-${RELEASE_TAG}-${INPUT_GOOS}-${INPUT_GOARCH}` by default. But people may want to add something else in the name, e.g., `date` or `shortsha`, etc.

**Comment by wangyoucao577** [comment]
One of the request is from https://github.com/wangyoucao577/go-release-action/issues/22

**Comment by chrislusf** [comment]
Maybe delete the previous one and add the new one.

**Comment by wangyoucao577** [comment]
Hi @chrislusf, please try out the new parameter `asset_name` on branch `wangyoucao577/go-release-action@feature/asset-name`. To set date in the name, you can      
- customize your date format and set to ENV 
```bash
- name: Set BUILD_TIME env
run: echo BUILD_TIME=$(date -u +%Y%m%d) >> ${GITHUB_ENV}
```
- append the information in asset name
```
asset_name: "binary-dev-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
```


For `delete the previous one`, I think it's a bit out of scope since the `go-release-action` exactly don't know what the `previous one` is. The [mknejp/delete-release-assets](https://github.com/mknejp/delete-release-assets) may help you. Use it to delete preivous ones, and use `go-release-action` to publish new ones make more sense.      

Let me know if any further question. Thanks!

**Comment by wangyoucao577** [comment]
@chrislusf Is it useful to you? I may postpone it if no one would like to use it. Let me know if any other idea. Thanks!

**Comment by chrislusf** [comment]
there are actually too many assets built already and I have to manually delete previous versions. If not including the auto delete the previous version, the storage will quickly run out. So I can not use it for now.

**Comment by wangyoucao577** [comment]
One possible approach to delete previous versions is combining the two actions together, as what I mentioned in https://github.com/wangyoucao577/go-release-action/issues/26#issuecomment-730277439. 
So I'll close this issue for now.  If any other idea, please feel free to reopen or create new issue to discuss. Thanks!

**Comment by wangyoucao577** [comment]
Hi @chrislusf, I'd love to see that you're indeed using the customize asset name feature! It's exciting! I have merged it to master, and released new version `wangyoucao577/go-release-action@v1.14`. Please integrate the stable version instead of feature branch. Let me know if any question. Thanks!

**Comment by chrislusf** [comment]
Thanks! Updated! I appreciate your work!
