### ISSUE TITLE
workflow_dispatch does not work

### ISSUE THREAD

**Issue by Xx0w0wxX** [wangyoucao577/go-release-action#29]
- https://github.com/Xx0w0wxX/gotan/runs/1477019308?check_suite_focus=true

> Unsupport event: workflow_dispatch!

Please apply it.

**Comment by wangyoucao577** [comment]
Could you please share the idea that why you add `workflow_dispatch` event? What's the behavior do you want to have?                 
I saw it appears on your error logs, but it's not exist in https://github.com/Xx0w0wxX/gotan/blob/6e713044d6c782f86e4dbc1c3afa8b52c8cf6e6e/.github/workflows/release.yaml#L5.

**Comment by Xx0w0wxX** [comment]
Sorry, I misunderstood the usage of your GitHub Actions.
