### ISSUE TITLE
how to skip a particular matrix combination

### ISSUE THREAD

**Issue by chrislusf** [wangyoucao577/go-release-action#30]
https://github.com/chrislusf/seaweedfs/actions/runs/429834210

This build needs most OS and ARCH combinations. However, the darwin and arm combination does not work, thus all other builds are cancelled. How to skip it?

**Comment by wangyoucao577** [comment]
Use 
```
        exclude:  
          - goarch: arm
            goos: darwin 
```
Here's an example: https://github.com/wangyoucao577/vt2geojson/blob/d413e3e02d147436a6d0c966459e1f126a186354/.github/workflows/release.yml#L19-L24

**Comment by chrislusf** [comment]
Great! Thanks for the fast reply!

**Comment by grosser** [comment]
... updating to latest fixed it 🤞
