### ISSUE TITLE
add support for private repositories ?

### ISSUE THREAD

**Issue by viggin543** [wangyoucao577/go-release-action#31]
upload assets fail on a private repo. 
github-assets-uploader  fails with the following error:

+ github-assets-uploader -f betzallel-v1.0.25-linux-amd64.tar.gz -mediatype application/gzip -repo xxx/xxx -token *** -tag v1.0.25
GET https://api.github.com/repos/xxx/xxx/releases/tags/v1.0.25: 404 Not Found []

**Comment by wangyoucao577** [comment]
It makes sense. Will provide it a little bit later.

**Comment by wangyoucao577** [comment]
@viggin543  Try out `wangyoucao577/go-release-action@v1.12` please.

**Comment by viggin543** [comment]
@wangyoucao577 
![image](https://user-images.githubusercontent.com/6231756/103190457-bebb9680-48d9-11eb-9c56-8cd35d16ffdd.png)
works like magic ! many thanks ! 🥇

**Comment by viggin543** [comment]
fixed by author
