### ISSUE TITLE
Allow manual triggers with 'workflow_dispatch'

### ISSUE THREAD

**Issue by cameronelliott** [wangyoucao577/go-release-action#35]
It is now possible to trigger actions manually: 
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

But this code fails cause it doesn't recognize the 'workflow_dispatch':
https://github.com/wangyoucao577/go-release-action/blob/1d13e5ecf97189f887b2d608bf2ab6349ec6d9a2/release.sh#L17

Please consider allowing 'workflow_dispatch' builds.

**Comment by wangyoucao577** [comment]
Nice! Will do!

**Comment by wangyoucao577** [comment]
@cameronelliott  Try `wangyoucao577/go-release-action@v1.13` please!

**Comment by cameronelliott** [comment]
@wangyoucao577 Sorry, I am busy with other stuff. I will try someday. Thank you for implementing.

**Comment by cameronelliott** [comment]
Sorry, for slow testing.

The build is using tag main but I need to put in actual release asset tag, which I am not doing correctly:
```
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
```

Do you know how I fix the inputs to set the tags correctly, so the `github-assets-uploader` tool uses my input and not `main` ?

```README.md
sfu-x186k
++ md5sum sfu-x186k-main-linux-amd64.tar.gz
++ cut -d ' ' -f 1
+ MD5_SUM=02ecf5f66d66261605f23cdaa0066072
++ sha256sum sfu-x186k-main-linux-amd64.tar.gz
++ cut -d ' ' -f 1
+ SHA256_SUM=76e0489082d1ee1544a8a5bb904ed42d3f65d0ea235bc7da1c483c709cf689bd
+ GITHUB_ASSETS_UPLOADR_EXTRA_OPTIONS=
+ '[' FALSE == TRUE ']'
+ github-assets-uploader -f sfu-x186k-main-linux-amd64.tar.gz -mediatype application/gzip -repo x186k/sfu-x186k -token *** -tag main
GET https://api.github.com/repos/x186k/sfu-x186k/releases/tags/main: 404 Not Found []
```

**Comment by wangyoucao577** [comment]
@cameronelliott  You need to do something like this: `release_tag: ${{ github.event.inputs.tags }}`
