### ISSUE TITLE
Option to skip archiving

### ISSUE THREAD

**Issue by siddharthab** [wangyoucao577/go-release-action#42]
Thank you for this project.

In some cases, e.g., when releasing only the binary file, it may be useful to release the files without archiving them to a .tar.gz or .zip first. In such cases, the files can be uploaded directly as individual files, following the asset naming convention.

**Comment by wangyoucao577** [comment]
OS or browser may report virus when download a executable binary, that's why I always uploads archives. Unarchive them is pretty easy on any computer. So could you please tell me an example that you really need raw binary instead of archive in some case?

**Comment by siddharthab** [comment]
No big reason. Just that it is easier for people to write bash scripts to download and run; saves one step of unarchiving. I did not think about the virus warnings. Please feel free to close this issue.

**Comment by wangyoucao577** [comment]
OK. Let me know if it's really needed in the future.
