### ISSUE TITLE
remove previous assets, by a name prefix?

### ISSUE THREAD

**Issue by chrislusf** [wangyoucao577/go-release-action#47]
Currently I am using `mknejp/delete-release-assets` https://github.com/chrislusf/seaweedfs/actions/workflows/cleanup.yml to remove previous assets. However, it stopped working 3 days ago with unknown reason.

Is it possible to add the feature to remove previous assets in this github action, e.g., by a name prefix?

**Comment by wangyoucao577** [comment]
`delete` is an danger operation. From my personal point of view, I still think it's not a good idea to bring such function in the current `go-release-action`. If necessary, I may create another action similar with `mknejp/delete-release-assets`. Fortuntely it's back to normal now, right?
