### ISSUE TITLE
Hidden extra_files (dotfiles) are not being packaged

### ISSUE THREAD

**Issue by flemeur** [wangyoucao577/go-release-action#51]
Hi

I have a hidden file that i want to include in the extra_files to be packaged along with the binary. This is currently not possible because the glob (*) does not include hidden files by default (here https://github.com/wangyoucao577/go-release-action/blob/master/release.sh#L79 and here https://github.com/wangyoucao577/go-release-action/blob/master/release.sh#L81).

I think an easy fix for this is to add the bash option  `shopt -s dotglob` at the top of the release script.

**Comment by wangyoucao577** [comment]
Add `shopt -s dotglob` may not good enough since it may affect the whole `bash`. I'm considering to add another option to support this, somethink like `archive_pattern: *`. And if you need to archive hidden files, you may set it by `archive_pattern: * .hidden_file`. Does it make sense to you?

**Comment by flemeur** [comment]
That is true. How about only enabling the setting for the package commands using a subshell? Like this:

```bash
( shopt -s dotglob; tar cvfz ${RELEASE_ASSET_NAME}${RELEASE_ASSET_EXT} * )
```

The `archive_pattern: *` setting could also work of course.

**Comment by wangyoucao577** [comment]
@flemeur  Oh, this would be better, e.g., limit the affection in a small group, so that we don't need to add another arg. Also, after archive we may restore it by `shopt -u dotglob`? Weclome PR to fix it! 😄

**Comment by flemeur** [comment]
@wangyoucao577 Done! :smile:
