### ISSUE TITLE
Support build from Makefile or free-form build_command

### ISSUE THREAD

**Issue by qrtt1** [wangyoucao577/go-release-action#54]
I am very thankful to see the great action helping us to release GO artifacts.

However, I already have a Makefile to build my binary with the application version information injection in the Makefile.

Examples:
```
LDFLAGS += -X my-module/hvalues.tagVersion=${VERSION}
LDFLAGS += -X my-module/hvalues.gitCommit=${GIT_COMMIT}
LDFLAGS += -X my-module/hvalues.gitTreeState=${GIT_DIRTY}
LDFLAGS += $(EXT_LDFLAGS)
```

## work around

My Makefile https://github.com/qrtt1/helm-values/blob/v0.1/Makefile

I know the action supports the LDFLAGS flag, but it doesn't make sense to duplicate LDFLAGS twice in the project.

It would be better to support a free-form build command to leverage existing build scripts or Makefile.

For now, I work around it:

```
     - uses: wangyoucao577/go-release-action@v1.18
	 with:
	 github_token: ${{ secrets.GITHUB_TOKEN }}
	 goos: ${{ matrix.goos }}
	 goarch: ${{ matrix.goarch }}
	 build_command: "make"
	 build_flags: "all"
	 binary_name: "helm-values"
	 ldflags: "-I."
	 extra_files: LICENSE README.md helm-values
```

**Comment by wangyoucao577** [comment]
It looks pretty useful. But this `make` approach can not work on windows, right?      
Could you please try to simplify the workaround as below:     
```
     - uses: wangyoucao577/go-release-action@v1.18
	 with:
	 github_token: ${{ secrets.GITHUB_TOKEN }}
	 goos: ${{ matrix.goos }}
	 goarch: ${{ matrix.goarch }}
	 build_command: "make all"
	 extra_files: LICENSE README.md helm-values
```
Then the only strange thing is that you have to use the `extra_files` to indicate the `helm-values` binary, because the action internal try to find the binary in subfolder by default.     
Maybe I can add one more option `build_artifacts_folder` that able to disable it, e.g., set `build_artifacts_folder: ""` to run the build command in root.

**Comment by wangyoucao577** [comment]
Oh..then I think I have to provide some way to customize the build phase, not only the build command, maybe something like `customized_build_phase: make all`. If it defined, `build_command/ldflags/build_flags` will be ignored.

**Comment by wangyoucao577** [comment]
@qrtt1  I have made a feature branch `feature/build-phase` that supports `make` in `build_command` directly, which seems more sensiable. Could you please help to have a try?       
Example:       
```
     - uses: wangyoucao577/go-release-action@feature/build-phase
	 with:
	 github_token: ${{ secrets.GITHUB_TOKEN }}
	 goos: ${{ matrix.goos }}
	 goarch: ${{ matrix.goarch }}
	 build_command: "make all"
	 binary_name: "helm-values"
	 extra_files: LICENSE README.md
```

**Comment by qrtt1** [comment]
@wangyoucao577 it works :D 
https://github.com/qrtt1/helm-values/actions/runs/1043733275

```
$  ls -l
total 7032
-rw-r--r--@ 1 qrtt1  staff    11357 Jul 19 10:32 LICENSE
-rw-r--r--@ 1 qrtt1  staff     1271 Jul 19 10:32 README.md
-rwxr-xr-x@ 1 qrtt1  staff  3580544 Jul 19 10:32 helm-values
```

```
$ ./helm-values
Usage of ./helm-values:
  -e string
    	regular expression filters
  -f string
    	the path of a values file (default "values.yaml")
  -i	interactive shell
  -v	show values
  -y	dump yaml (it works with the filter)

version.BuildInfo{"Version":"v0.1-lab","GitCommit":"72e5809fbce878aecb93a457575704a3ad2b5a57","GitTreeState":"clean","GoVersion":"go1.16.2"}
```

**Comment by wangyoucao577** [comment]
@qrtt1  Great! Please use the released version instead:    
```
- name: Go Release Binaries
  uses: wangyoucao577/go-release-action@v1.19

```
