### ISSUE TITLE
Need to support go 1.17

### ISSUE THREAD

**Issue by chrislusf** [wangyoucao577/go-release-action#59]
Ideally, do not hard code the supported go versions

**Comment by wangyoucao577** [comment]
Please check out `wangyoucao577/go-release-action@v1.20` to have a try. It'll use the latest go version by default(current go1.17), no need to upgrade the action or hardcode go version anymore. You can also explicitly set something like `1.16` or `1.17` to lock the version if you'd like to.

**Comment by chrislusf** [comment]
thanks!
