### ISSUE TITLE
 github-assets-uploader  failed after retry 3 times

### ISSUE THREAD

**Issue by lixiaofei123** [wangyoucao577/go-release-action#68]
version:  wangyoucao577/go-release-action@v1.22

+ github-assets-uploader -logtostderr -f nextlist-v0.0.2-linux-amd64.tar.gz -mediatype application/gzip -repo lixiaofei123/nextlist -token *** -tag v0.0.2 -retry 3
W1230 03:17:02.208636    1152 main.go:56] Upload asset error, will retry soon: Post "https://uploads.github.com/repos/lixiaofei123/nextlist/releases/56169675/assets?name=nextlist-v0.0.2-linux-amd64.tar.gz": write tcp 172.17.0.2:51786->140.82.114.14:443: write: connection reset by peer
W1230 03:17:05.897318    1152 main.go:56] Upload asset error, will retry soon: Post "https://uploads.github.com/repos/lixiaofei123/nextlist/releases/56169675/assets?name=nextlist-v0.0.2-linux-amd64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 1; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error
E1230 03:17:09.406906    1152 main.go:20] Post "https://uploads.github.com/repos/lixiaofei123/nextlist/releases/56169675/assets?name=nextlist-v0.0.2-linux-amd64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 3; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error

**Comment by wangyoucao577** [comment]
It's something wrong of the Github platform. The only way we can do is increasing the retry parameter for now. Please try to increase it to `retry: 10` or more.

**Comment by eumel8** [comment]
@wangyoucao577 I have additional error

```
W0104 13:09:28.196443    2443 main.go:56] Upload asset error, will retry soon: POST https://uploads.github.com/repos/eumel8/overlaytest/releases/56374579/assets?name=overlaytest-0.0.5-linux-arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

It's working mostly, but sometimes failed. As you said something is wrong on the Github platform, but maybe there is a way to get more robustness. But thanks in general for sharing this great Action!

**Comment by wangyoucao577** [comment]
This error `already_exists` shows that it has been uploaded to github even the previously error code is still fail. You can add `overwrite: true` if you hope no such error again.      

It had been quite stable in last months. However, nowdays I saw some errors like this, not only this action, but other similars which upload assets to github. I believe this one(the `go-release-action`) is the robust one compare with others, since it has provided the `retry` logic to avoid most of errors. I have no idea to do any improvement unless Github make the upload API more stable.

**Comment by eumel8** [comment]
@wangyoucao577 thanks again, `overwrite: true` seems helpful

**Comment by lixiaofei123** [comment]
Set retry to 10 does not seem to help much, also will github will fix the problem

**Comment by sanjP10** [comment]
I also had the same issue adding `retry: 10` and `overwrite: true` worked

**Comment by lixiaofei123** [comment]
@sanjP10  thanks.it works
