### ISSUE TITLE
need post_command feature to do some teardown work

### ISSUE THREAD

**Issue by debugtalk** [wangyoucao577/go-release-action#70]
I want to do some teardown work after releasing, such as publishing artifacts to aliyun OSS as well.

However, when I do this work in next step, I can not get `BUILD_ARTIFACTS_FOLDER` environment as they are in different steps. Thus I think it maybe useful if we can have a new `post_command` feature like `pre_command`.

**Comment by wangyoucao577** [comment]
Sounds good.  PR is welcomed!

**Comment by debugtalk** [comment]
@wangyoucao577 please check and review

 https://github.com/wangyoucao577/go-release-action/pull/71

**Comment by wangyoucao577** [comment]
Closed by https://github.com/wangyoucao577/go-release-action/pull/71
