### ISSUE TITLE
Failed to upload asset

### ISSUE THREAD

**Issue by danvixent** [wangyoucao577/go-release-action#79]
/usr/bin/docker run --name ghcriowangyoucao577goreleaseactionv125_bf049b --label 29a95e --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_GOOS -e INPUT_GOARCH -e INPUT_GOVERSION -e INPUT_PROJECT_PATH -e INPUT_BINARY_NAME -e INPUT_EXTRA_FILES -e INPUT_BUILD_FLAGS -e INPUT_LDFLAGS -e INPUT_PRE_COMMAND -e INPUT_BUILD_COMMAND -e INPUT_EXECUTABLE_COMPRESSION -e INPUT_MD5SUM -e INPUT_SHA256SUM -e INPUT_RELEASE_TAG -e INPUT_RELEASE_NAME -e INPUT_OVERWRITE -e INPUT_ASSET_NAME -e INPUT_RETRY -e INPUT_POST_COMMAND -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/certgen/certgen":"/github/workspace" ghcr.io/wangyoucao577/go-release-action:v1.25  "***" "linux" "amd64" "1.17" "" "" "." "certgen" "" "go build" "" "LICENSE README.md" "TRUE" "FALSE" "" "" "FALSE" "" "3" ""
+ source /setup-go.sh
+++ curl 'https://go.dev/VERSION?m=text'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     8  100     8    0     0     54      0 --:--:-- --:--:-- --:--:--    54
++ GO_LINUX_PACKAGE_URL=https://dl.google.com/go/go1.17.8.linux-amd64.tar.gz
++ [[ 1.17 == \1\.\1\7 ]]
++ GO_LINUX_PACKAGE_URL=https://go.dev/dl/go1.17.linux-amd64.tar.gz
++ wget --progress=dot:mega https://go.dev/dl/go1.17.linux-amd64.tar.gz -O go-linux.tar.gz
--2022-03-11 14:21:47--  https://go.dev/dl/go1.17.linux-amd64.tar.gz
Resolving go.dev (go.dev)... 216.239.38.21, 216.239.36.21, 216.239.34.21, ...
Connecting to go.dev (go.dev)|216.239.38.21|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.google.com/go/go1.17.linux-amd64.tar.gz [following]
--2022-03-11 14:21:47--  https://dl.google.com/go/go1.17.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 142.250.138.93, 142.250.138.136, 142.250.138.190, ...
Connecting to dl.google.com (dl.google.com)|142.250.138.93|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 134787877 (129M) [application/x-gzip]
Saving to: 'go-linux.tar.gz'

     0K ........ ........ ........ ........ ........ ........  2% 48.2M 3s
  3072K ........ ........ ........ ........ ........ ........  4%  132M 2s
  6144K ........ ........ ........ ........ ........ ........  7% 33.7M 2s
  9216K ........ ........ ........ ........ ........ ........  9%  197M 2s
 12288K ........ ........ ........ ........ ........ ........ 11% 28.2M 2s
 15360K ........ ........ ........ ........ ........ ........ 14%  164M 2s
 18432K ........ ........ ........ ........ ........ ........ 16% 39.4M 2s
 21504K ........ ........ ........ ........ ........ ........ 18% 54.4M 2s
 24576K ........ ........ ........ ........ ........ ........ 21%  118M 2s
 27648K ........ ........ ........ ........ ........ ........ 23% 54.4M 2s
 30720K ........ ........ ........ ........ ........ ........ 25% 64.1M 2s
 33792K ........ ........ ........ ........ ........ ........ 28%  203M 2s
 36864K ........ ........ ........ ........ ........ ........ 30% 30.5M 2s
 39936K ........ ........ ........ ........ ........ ........ 32%  149M 1s
 43008K ........ ........ ........ ........ ........ ........ 35% 38.0M 1s
 46080K ........ ........ ........ ........ ........ ........ 37% 85.7M 1s
 49152K ........ ........ ........ ........ ........ ........ 39% 66.2M 1s
 52224K ........ ........ ........ ........ ........ ........ 42% 38.9M 1s
 55296K ........ ........ ........ ........ ........ ........ 44%  203M 1s
 58368K ........ ........ ........ ........ ........ ........ 46% 28.4M 1s
 61440K ........ ........ ........ ........ ........ ........ 49%  192M 1s
 64512K ........ ........ ........ ........ ........ ........ 51% 25.4M 1s
 67584K ........ ........ ........ ........ ........ ........ 53%  183M 1s
 70656K ........ ........ ........ ........ ........ ........ 56% 44.3M 1s
 73728K ........ ........ ........ ........ ........ ........ 58% 85.4M 1s
 76800K ........ ........ ........ ........ ........ ........ 60% 35.0M 1s
 79872K ........ ........ ........ ........ ........ ........ 63%  199M 1s
 82944K ........ ........ ........ ........ ........ ........ 65% 43.2M 1s
 86016K ........ ........ ........ ........ ........ ........ 67% 63.0M 1s
 89088K ........ ........ ........ ........ ........ ........ 70%  111M 1s
 92160K ........ ........ ........ ........ ........ ........ 72% 70.2M 1s
 95232K ........ ........ ........ ........ ........ ........ 74% 36.9M 1s
 98304K ........ ........ ........ ........ ........ ........ 77%  202M 1s
101376K ........ ........ ........ ........ ........ ........ 79% 42.6M 0s
[104](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:104)448K ........ ........ ........ ........ ........ ........ 81% 64.4M 0s
107520K ........ ........ ........ ........ ........ ........ 84% 57.0M 0s
1[105](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:105)92K ........ ........ ........ ........ ........ ........ 86% 64.9M 0s
[113](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:113)664K ........ ........ ........ ........ ........ ........ 88% 93.2M 0s
[116](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:116)736K ........ ........ ........ ........ ........ ........ 91% 57.3M 0s
[119](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:119)808K ........ ........ ........ ........ ........ ........ 93% 94.5M 0s
122880K ........ ........ ........ ........ ........ ........ 95% 17.2M 0s
125952K ........ ........ ........ ........ ........ ........ 98%  156M 0s
129024K ........ ........ ........ ........ ........         100% 49.2M=2.3s

2022-03-11 14:21:50 (56.5 MB/s) - 'go-linux.tar.gz' saved [134787877/134787877]

++ tar -zxf go-linux.tar.gz
++ mv go /usr/local/
++ mkdir -p /go/bin /go/src /go/pkg
++ export GO_HOME=/usr/local/go
++ GO_HOME=/usr/local/go
++ export GOPATH=/go
++ GOPATH=/go
++ export PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ go version
+ env
go version go1.17 linux/amd64
+ /release.sh
INPUT_GOARCH=amd64
INPUT_RETRY=3
INPUT_GOVERSION=1.17
HOSTNAME=c9910563b33a
GITHUB_REF_NAME=v0.1.0
INPUT_ASSET_NAME=
GITHUB_API_URL=https://api.github.com
INPUT_PROJECT_PATH=.
INPUT_MD5SUM=TRUE
GITHUB_STEP_SUMMARY=/github/file_commands/step_summary_b00f0c9f-8263-46b7-bc9e-ac33ac14836b
GITHUB_RUN_ATTEMPT=1
RUNNER_TOOL_CACHE=/opt/hostedtoolcache
GITHUB_REPOSITORY_OWNER=danvixent
GITHUB_ACTIONS=true
CI=true
GITHUB_HEAD_REF=
GITHUB_ACTOR=danvixent
GITHUB_ACTION_REF=v1.25
INPUT_OVERWRITE=FALSE
GOPATH=/go
GITHUB_ACTION=__wangyoucao577_go-release-action
INPUT_BINARY_NAME=certgen
GITHUB_REF_PROTECTED=false
INPUT_POST_COMMAND=
INPUT_LDFLAGS=
***
HOME=/github/home
INPUT_BUILD_FLAGS=
GITHUB_ACTION_REPOSITORY=wangyoucao577/go-release-action
GITHUB_REF_TYPE=tag
++ basename danvixent/certgen
RUNNER_TEMP=/home/runner/work/_temp
GITHUB_RETENTION_DAYS=90
INPUT_EXTRA_FILES=LICENSE README.md
INPUT_RELEASE_NAME=
GITHUB_ENV=/github/file_commands/set_env_b00f0c9f-8263-46b7-bc9e-ac33ac14836b
RUNNER_WORKSPACE=/home/runner/work/certgen
GITHUB_REF=refs/tags/v0.1.0
+ BINARY_NAME=certgen
GITHUB_SHA=51e1c7a514d1fb37a8f43f6a4755c06a88af9091
+ '[' xcertgen '!=' x ']'
ACTIONS_RUNTIME_TOKEN=***
+ BINARY_NAME=certgen
++ basename refs/tags/v0.1.0
+ RELEASE_TAG=v0.1.0
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ RELEASE_NAME=
+ RELEASE_ASSET_NAME=certgen-v0.1.0-linux-amd64
+ '[' '!' -z '' ']'
+ '[' push == release ']'
+ '[' push == push ']'
+ echo 'Event: push'
+ '[' '!' -z '' ']'
+ EXT=
+ '[' linux == windows ']'
+ LDFLAGS_PREFIX=
+ '[' '!' -z '' ']'
++ date +%s
+ BUILD_ARTIFACTS_FOLDER=build-artifacts-1647008514
+ mkdir -p ./build-artifacts-1647008514
+ cd .
+ [[ go build =~ ^make.* ]]
+ GOOS=linux
+ GOARCH=amd64
+ go build -o build-artifacts-1647008514/certgen ''
GITHUB_RUN_ID=1969254757
RUNNER_ARCH=X64
GITHUB_SERVER_URL=https://github.com
GO_HOME=/usr/local/go
GITHUB_EVENT_PATH=/github/workflow/event.json
INPUT_GOOS=linux
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
RUNNER_OS=Linux
GITHUB_BASE_REF=
INPUT_SHA256SUM=FALSE
INPUT_BUILD_COMMAND=go build
GITHUB_PATH=/github/file_commands/add_path_b00f0c9f-8263-46b7-bc9e-ac33ac14836b
INPUT_RELEASE_TAG=
GITHUB_JOB=release-matrix
RUNNER_NAME=GitHub Actions 2
INPUT_EXECUTABLE_COMPRESSION=
SHLVL=1
GITHUB_REPOSITORY=danvixent/certgen
INPUT_PRE_COMMAND=
GITHUB_EVENT_NAME=push
GITHUB_RUN_NUMBER=1
GITHUB_WORKFLOW=Release Go Binaries
PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GITHUB_WORKSPACE=/github/workspace
ACTIONS_RUNTIME_URL=https://pipelines.actions.githubusercontent.com/Ok77YWRkg9KTXsXpByBeLrItOG8jYGZzlqCWiMBBnwqM4eJmZV/
ACTIONS_CACHE_URL=https://artifactcache.actions.githubusercontent.com/Ok77YWRkg9KTXsXpByBeLrItOG8jYGZzlqCWiMBBnwqM4eJmZV/
INPUT_GITHUB_TOKEN=***
_=/usr/bin/env
Event: push
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
+ '[' '!' -z '' ']'
+ '[' '!' -z 'LICENSE README.md' ']'
+ cd /github/workspace
+ cp -r LICENSE README.md ./build-artifacts-1647008514/
+ cd .
+ cd build-artifacts-1647008514
+ ls -lha
+ RELEASE_ASSET_EXT=.tar.gz
+ MEDIA_TYPE=application/gzip
total 6.3M
drwxr-xr-x 2 root root 4.0K Mar 11 14:21 .
drwxr-xr-x 5 1001  [121](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:121) 4.0K Mar 11 14:21 ..
-rw-r--r-- 1 root root  34K Mar 11 14:21 LICENSE
-rw-r--r-- 1 root root 1.2K Mar 11 14:21 README.md
-rwxr-xr-x 1 root root 6.3M Mar 11 14:21 certgen
+ RELEASE_ASSET_FILE=certgen-v0.1.0-linux-amd64.tar.gz
+ '[' linux == windows ']'
+ shopt -s dotglob
+ tar cvfz certgen-v0.1.0-linux-amd64.tar.gz LICENSE README.md certgen
LICENSE
README.md
certgen
++ md5sum certgen-v0.1.0-linux-amd64.tar.gz
++ cut -d ' ' -f 1
+ MD5_SUM=9d8a0c299de3602a52b67aef73ec81ef
++ sha256sum certgen-v0.1.0-linux-amd64.tar.gz
++ cut -d ' ' -f 1
+ SHA256_SUM=73776f46b5a72c82586b39ab7ef0b4cec1ad40cc23[135](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:135)12db4[180](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:180)d2e074baaab
+ GITHUB_ASSETS_UPLOADR_EXTRA_OPTIONS=
+ '[' FALSE == TRUE ']'
+ github-assets-uploader -logtostderr -f certgen-v0.1.0-linux-amd64.tar.gz -mediatype application/gzip -repo danvixent/certgen -token *** -tag=v0.1.0 -releasename= -retry 3
W0311 14:21:56.610551     101 main.go:58] Upload asset error, will retry in 3s: GET https://api.github.com//repos/danvixent/certgen/releases/tags/v0.1.0: 404 Not Found []
W0311 14:21:59.72[210](https://github.com/danvixent/certgen/runs/5512154141?check_suite_focus=true#step:4:210)5     101 main.go:58] Upload asset error, will retry in 3s: GET https://api.github.com/repos/danvixent/certgen/releases/tags/v0.1.0: 404 Not Found []
E0311 14:22:02.834961     101 main.go:21] GET https://api.github.com/repos/danvixent/certgen/releases/tags/v0.1.0: 404 Not Found []

The action keeps failing to upload assets, any help is appreciated !

**Comment by wangyoucao577** [comment]
You need to replace 
```
on:
  push:
    tags:
      # Release binary for every tag.
      - v0.*
```
by 
```
on:
  release:
    types: [created]
```

It will run whenever you create a new release.

**Comment by danvixent** [comment]
Thanks!
