### ISSUE TITLE
How to disable executable_compression

### ISSUE THREAD

**Issue by pablodz** [wangyoucao577/go-release-action#88]
How to disable executable_compression

**Comment by wangyoucao577** [comment]
With the latest version `wangyoucao577/go-release-action@v1.29`, now you can use `compress_assets: false`.

**Comment by pablodz** [comment]
Thanks

**Comment by pablodz** [comment]
Check this log https://github.com/pablodz/sherlockgo/actions/runs/2580710135

This is mi config yaml https://github.com/pablodz/sherlockgo/blob/main/.github/workflows/release.yml

```

+ GITHUB_ASSETS_UPLOADR_EXTRA_OPTIONS=
+ '[' FALSE == TRUE ']'
+ github-assets-uploader -logtostderr -f sherlockgo-v0.0.11-5-linux-386 -mediatype application/octet-stream -repo pablodz/sherlockgo -token *** -tag=v0.0.11-5 -releasename= -retry 3
W0629 04:32:50.724674    1364 main.go:58] Upload asset error, will retry in 3s: open sherlockgo-v0.0.11-5-linux-386: no such file or directory
W0629 04:32:53.836824    1364 main.go:58] Upload asset error, will retry in 3s: open sherlockgo-v0.0.11-5-linux-386: no such file or directory
E0629 04:32:56.939555    1364 main.go:21] open sherlockgo-v0.0.11-5-linux-386: no such file or directory
```

**Comment by wangyoucao577** [comment]
It's a bug that binary can not be found if it has different name of asset_name after disable compression. I will fix it later.          

For now, you can try out workaround as below:        

```
    binary_name: sherlockgo-${{ matrix.goos }}-${{ matrix.goarch }}
    asset_name: sherlockgo-${{ matrix.goos }}-${{ matrix.goarch }}
```

By the way, currently `extra_files` will NOT be handled if compression disabled.

**Comment by dclong** [comment]
The tag "compress_asserts" doesn't seem to work.

**Comment by hotrush** [comment]
@wangyoucao577 this workaround doesn't work for windows binaries because of exe extension

**Comment by wangyoucao577** [comment]
Try out `wangyoucao577/go-release-action@v1.30` please!

**Comment by pablodz** [comment]
It works, thanks x2
