### ISSUE TITLE
failed to upload assets to github release

### ISSUE THREAD

**Issue by Wsine** [wangyoucao577/go-release-action#91]
the execution results can be seen here: https://github.com/Wsine/feishu2md/actions/runs/2796731279

I read the relatived issues and I am confirmed with that

- I used the latest released version of go-release-action
- I ran at ubuntu-latest image
- I triggered the event with release create
- I reruned the action 3 times, in which there were 3 retries for each rerunning

are there something else I am missing?

**Comment by wangyoucao577** [comment]
It considered to be a bug of `net/http` which seems have been resolved several years ago, not sure why happen again. Refer to https://github.com/wangyoucao577/go-release-action/issues/63#issuecomment-965271772 for more details.            
Try add `export GODEBUG=http2client=0` in your `pre_command`, and here's a full example of this:        
 
https://github.com/seaweedfs/seaweedfs/blob/e134570a9ceac1084f01a6b223891262a6628ab9/.github/workflows/binaries_dev.yml#L103

**Comment by Wsine** [comment]
@wangyoucao577 thanks for the reply.

I tried this solution, but it still didn't work. see https://github.com/Wsine/feishu2md/actions/runs/2815542864

I can not observe any difference in the output, except that command.

I even configured the number of retry to 10.

**Comment by wangyoucao577** [comment]
@Wsine  Now the logs show differerent issue: `W0808 05:10:00.824353     371 main.go:58] Upload asset error, will retry in 3s: POST https://uploads.github.com/repos/Wsine/feishu2md/releases/73854128/assets?name=feishu2md-v1.0.1-linux-amd64.tar.gz: 403 Resource not accessible by integration []`      

Did you change the permission behavior in your project? Somthing like Settings -> Actions -> Workflow permissions, etc. You may need to assign `Read and Write` permission for your project, or add necessary permissions from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

**Comment by Wsine** [comment]
@wangyoucao577 OK, thanks a lot, it did resolve the problem.

Before adding the `GODEBUG=http2client=0` env, this error message happened occasionally.

I looked for the GitHub doc to find out that the default permission is  good for write permission, so I did not change the setting manually.

Maybe adding this setting to the README would be more helpful.

Anyway, thanks a lot for the help.

**Comment by wangyoucao577** [comment]
Welcome PR to metion it 😃
