### ISSUE TITLE
Can I use go version defined in go.mod?

### ISSUE THREAD

**Issue by hmiyado** [wangyoucao577/go-release-action#99]
Hello,

[actions/setup-go](https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file) accepts go.mod and use the version defined in it.

Can I use the goversion like it?

**Comment by wangyoucao577** [comment]
It's an independent feature that doesn't implemented at the moment.

**Comment by hmiyado** [comment]
Thanks for the answer.
If you feel this looks like a good feature, I would be happy to develop it in the future.

**Comment by wangyoucao577** [comment]
PR is always welcome! :smiley:
